#!/usr/bin/env bash

#
# esce dallo script
#
function die()
{
    local messages=( "${@}" )
    local message

    for message in "${messages[@]}"
    do
        echo "FATAL | ${message}"
    done
    echo "FATAL | Termino programma"
    # echo "FATAL | per consultare log aprire: ${LOGFILE}"
    # echo "FATAL | * * * * PER ASSISTENZA MANDARE file '$(basename ${LOGFILE})' * * * *"
    exit 1
}

SCRIPTPATH="$(dirname "${0}")"              # percorso script == percorso dati
echo SCRIPTPATH=$SCRIPTPATH
CONFIGPATH="${SCRIPTPATH}"                  # percorso dati == percorso script
INCLUDEPATH="${SCRIPTPATH}"                 # percorso dati == percorso script
#############################################################################
#
# CONFIGURAZIONE AMBIENTE
#
#############################################################################
CONFIG="${CONFIGPATH}/config.include"
. "${CONFIG}" || die "impossibile caricare ${CONFIG}"
#############################################################################
#
# FUNZIONI
#
#############################################################################
INCLUDE="${INCLUDEPATH}/functions.include"
. "${INCLUDE}" || die "impossibile caricare ${INCLUDE}"

function main()
{
    info main

    info "${0}: param num ${#}"
    info "${0}: params ${@}"

    get_options "${@}"

    info "${0}: param num ${#}"
    info "${0}: params ${@}"

    exit

    if [ ${#} -eq 0 ]
    then
        status
    elif [ ${1,,} = on ]
    then
        echo "set wifi on"
    elif [ ${1,,} = off ]
    then
        echo "set wifi off"
    fi
}

main "${@}"
