#!/usr/bin/env bash

# ls /etc/netplan
# 00-ethernet.yaml  00-installer-config.yaml.BACKUP  01-wifi.yaml  bad

NETPLAN_PATH=/etc/netplan
ETH_FILENAME=00-ethernet.yaml
WIFI_FILENAME=01-wifi.yaml

ETH="${NETPLAN_PATH}/${ETH_FILENAME}"
WIFI="${NETPLAN_PATH}/${WIFI_FILENAME}"

function get_status() 
{	
	local config=${1}
	[ -f ${config} ] && { echo "ACTIVATED"; } || { echo "DEACTIVATED"; }
}
function wifi_status() { echo "wifi is $(get_status ${WIFI}) in netplan"; }
function eth_status() { echo "eth is $(get_status ${ETH}) in netplan"; }

function status()
{
	echo "NETPLAN connection status:"
	eth_status
	wifi_status
}


echo "${0}: param num ${#}"
echo "${0}: params ${@}"

if [ ${#} -eq 0 ]
then
	status
elif [ ${1,,} = on ]
then
	echo "set wifi on"
elif [ ${1,,} = off ]
then
	echo "set wifi off"
fi
